In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
movie = pd.read_csv('/content/drive/MyDrive/pattern Recognition/movies.csv')
rating = pd.read_csv('/content/drive/MyDrive/pattern Recognition/ratings.csv')

In [ ]:
movie.head()

   movieId  ...                                       genres
0        1  ...  Adventure|Animation|Children|Comedy|Fantasy
1        2  ...                   Adventure|Children|Fantasy
2        3  ...                               Comedy|Romance
3        4  ...                         Comedy|Drama|Romance
4        5  ...                                       Comedy

[5 rows x 3 columns]

In [ ]:
rating.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [ ]:
print(movie.shape)
print(rating.shape)

(9742, 3)
(100836, 4)

In [ ]:
print(movie.info())
print(rating.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB
None

In [ ]:
print(movie.describe())
print(rating.describe())

             movieId
count    9742.000000
mean    42200.353623
std     52160.494854
min         1.000000
25%      3248.250000
50%      7300.000000
75%     76232.000000
max    193609.000000
              userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

In [ ]:
print(movie.dtypes)
print(rating.dtypes)

movieId     int64
title      object
genres     object
dtype: object
userId         int64
movieId        int64
rating       float64
timestamp      int64
dtype: object

In [ ]:
#CREATING NEW DATASET
df = rating.pivot(index = 'movieId', columns = 'userId', values = 'rating')
df.head()

userId   1    2    3    4    5    6    7    ...  604  605  606  607  608  609  610
movieId                                     ...
1        4.0  NaN  NaN  NaN  4.0  NaN  4.5  ...  3.0  4.0  2.5  4.0  2.5  3.0  5.0
2        NaN  NaN  NaN  NaN  NaN  4.0  NaN  ...  5.0  3.5  NaN  NaN  2.0  NaN  NaN
3        4.0  NaN  NaN  NaN  NaN  5.0  NaN  ...  NaN  NaN  NaN  NaN  2.0  NaN  NaN
4        NaN  NaN  NaN  NaN  NaN  3.0  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5        NaN  NaN  NaN  NaN  NaN  5.0  NaN  ...  3.0  NaN  NaN  NaN  NaN  NaN  NaN

[5 rows x 610 columns]

In [ ]:
df=df.fillna(0)
df

userId   1    2    3    4    5    6    7    ...  604  605  606  607  608  609  610
movieId                                     ...
1        4.0  0.0  0.0  0.0  4.0  0.0  4.5  ...  3.0  4.0  2.5  4.0  2.5  3.0  5.0
2        0.0  0.0  0.0  0.0  0.0  4.0  0.0  ...  5.0  3.5  0.0  0.0  2.0  0.0  0.0
3        4.0  0.0  0.0  0.0  0.0  5.0  0.0  ...  0.0  0.0  0.0  0.0  2.0  0.0  0.0
4        0.0  0.0  0.0  0.0  0.0  3.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5        0.0  0.0  0.0  0.0  0.0  5.0  0.0  ...  3.0  0.0  0.0  0.0  0.0  0.0  0.0
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
193581   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
193583   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
193585   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
193587   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
193609   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[9724 rows x 610 columns]

In [ ]:
no_user_voted = rating.groupby('movieId')['rating'].agg('count')
no_user_voted

movieId
1         215
2         110
3          52
4           7
5          49
         ...
193581      1
193583      1
193585      1
193587      1
193609      1
Name: rating, Length: 9724, dtype: int64

In [ ]:
no_movies_voted = rating.groupby('userId')['rating'].agg('count')
no_movies_voted

userId
1       232
2        29
3        39
4       216
5        44
       ...
606    1115
607     187
608     831
609      37
610    1302
Name: rating, Length: 610, dtype: int64

In [ ]:
from scipy.sparse import csr_matrix

In [ ]:
#remove sparsity
df2 = csr_matrix(df.values)
df.reset_index(inplace = True)

In [ ]:
#creating model using knn
from sklearn.neighbors import NearestNeighbors
knn = NearestNeighbors(metric = 'cosine', algorithm = 'brute', n_neighbors = 20, n_jobs = -1)
knn.fit(df2)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=-1, n_neighbors=20, p=2,
                 radius=1.0)

In [ ]:
df1=df

In [ ]:
#creating function for recommendation
global df
def recommend(movie_name):
    movie_to_recommend = 10
    movie_list = movie[movie['title'].str.contains(movie_name)]
    if len(movie_list):
        movie_id = movie_list.iloc[0]['movieId']
        movie_id = df1[df1['movieId'] == movie_id].index[0]
        
        distances, indices = knn.kneighbors(df2[movie_id], n_neighbors = movie_to_recommend +1)
        movie_indices = sorted(list(zip(indices.squeeze().tolist(), distances.squeeze().tolist())), key = lambda x :x[1])[:0:-1]
        
         
        recommend_frame = []
        for i in movie_indices:
            movie_id = df1.iloc[i[0]]['movieId']
            id_ = movie[movie['movieId'] == movie_id].index
            
            recommend_frame.append({'Title': movie.iloc[id_]['title'].values[0], 'distance': i[1]})
            
        df = pd.DataFrame(recommend_frame, index=range(1, movie_to_recommend+1))
        return df
    else:
        return 'No movies found. Check input.'

In [ ]:
recommend('Iron Man 2')

                                         Title  distance
1                                  Thor (2011)  0.412239
2                               Ant-Man (2015)  0.402586
3    Captain America: The First Avenger (2011)  0.399933
4   Captain America: The Winter Soldier (2014)  0.396864
5               Avengers: Age of Ultron (2015)  0.395493
6               Guardians of the Galaxy (2014)  0.361573
7                              Iron Man (2008)  0.358014
8                            Iron Man 3 (2013)  0.322434
9                         Avengers, The (2012)  0.304676
10                   X-Men: First Class (2011)  0.300476

In [ ]:
recommend('Toy Story')

                                                Title  distance
1                           Back to the Future (1985)  0.469619
2                                Groundhog Day (1993)  0.465831
3                          Mission: Impossible (1996)  0.461087
4   Star Wars: Episode VI - Return of the Jedi (1983)  0.458911
5                               Lion King, The (1994)  0.458855
6                                 Forrest Gump (1994)  0.452904
7           Star Wars: Episode IV - A New Hope (1977)  0.442612
8                Independence Day (a.k.a. ID4) (1996)  0.435738
9                                Jurassic Park (1993)  0.434363
10                                 Toy Story 2 (1999)  0.427399

In [ ]:
recommend('Father of the Bride')

                                         Title  distance
1                               Tin Cup (1996)  0.599858
2   Willy Wonka & the Chocolate Factory (1971)  0.599087
3                               Twister (1996)  0.598490
4                            Sgt. Bilko (1996)  0.590676
5                Miracle on 34th Street (1994)  0.583797
6                      Grumpier Old Men (1995)  0.582198
7                    Mr. Holland's Opus (1995)  0.581243
8                            Striptease (1996)  0.574330
9                            Juror, The (1996)  0.534414
10                              Sabrina (1995)  0.525998

In [ ]:
recommend("Naruto")

'No movies found. Check input.'

In [ ]:
recommend("Bungo Stray Dogs")

                                                Title  distance
1              Kizumonogatari Part 1: Tekketsu (2016)       0.0
2             The Night Is Short, Walk on Girl (2017)       0.0
3                                 The Thinning (2016)       0.0
4                                    Ferdinand (2017)       0.0
5   Fullmetal Alchemist: The Sacred Star of Milos ...       0.0
6   Too Funny to Fail: The Life and Death of The D...       0.0
7               The Stanford Prison Experiment (2015)       0.0
8                                  The Clapper (2018)       0.0
9                     Fullmetal Alchemist 2018 (2017)       0.0
10                                     Bakuman (2015)       0.0